//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by app.rc
//
#define IDS_PLUGIN_NAME                 0
#define IDS_NEW_VERSION_AVAILABLE       1
#define IDS_DISABLE_UPDATE_CHECK        2
#define IDS_OPEN_DOWNLOAD_PAGE          3
#define IDS_INFORMATION                 6
#define LWS_USEVISUALSTYLE              0x0008
#define IDS_ON                          8
#define IDS_OFF                         9
#define IDS_PREVIOUS                    10
#define IDS_PAUSE                       11
#define IDS_PLAY                        12
#define IDS_STOP                        13
#define IDS_NEXT                        14
#define IDS_ERROR_SETTING_THUMBNAIL     15
#define IDS_PLAYING                     16
#define IDS_PAUSED                      17
#define IDS_STOPPED                     18
#define IDS_TASKBAR_INITIALIZE_FAILURE  19
#define IDS_ALL_IMAGE_FORMATS           20
#define IDS_USE_AS_THUMB_BKGND          21
#define IDS_SELECT_IMAGE_FILE           22
#define IDS_MOD_PLAYER_BUTTONS_RESTART  23
#define IDS_APPLYING_SETTINGS           24
#define IDS_HELP1                       25
#define IDS_HELP2                       26
#define IDS_HELP3                       27
#define IDS_HELP5                       28
#define IDS_HELP6                       29
#define IDS_HELP7                       30
#define IDS_HELP8                       31
#define LWS_RIGHT                       0x0020
#define IDS_HELP9                       32
#define IDS_HELP10                      33
#define IDS_HELP11                      34
#define IDS_HELP12                      35
#define IDS_HELP13                      36
#define IDS_HELP14                      37
#define IDS_HELP15                      38
#define IDS_HELP16                      39
#define IDS_HELP17                      40
#define IDS_HELP18                      41
#define IDS_HELP19                      42
#define IDS_HELP20                      43
#define IDS_HELP21                      44
#define IDS_TRANSPARENT                 46
#define IDS_ALBUM_ART                   47
#define IDS_DEFAULT_BACKGROUND          48
#define IDS_CUSTOM_BACKGROUND           49
#define IDS_TASKBAR_ICON                53
#define IDS_JUMPLIST                    58
#define IDS_DEVELOPMENT                 71
#define IDS_OPTIONS                     72
#define IDS_TEXT                        73
#define IDS_BACKGROUND                  74
#define IDS_VOLUME_UP                   80
#define IDS_VOLUME_DOWN                 81
#define IDS_OPEN_FILE                   82
#define IDS_WINAMP_PREFERENCES          84
#define IDS_PLEASE_START_WINAMP_FIRST   85
#define IDS_ERROR_CREATING_JUMP_LIST    86
#define IDS_CREDITs                     92
#define IDS_RESUME_PLAYBACK             94
#define IDS_PLAY_FROM_BEGINNING         95
#define IDS_HELP22                      96
#define IDS_HELP23                      97
#define IDS_BOOKMARKS                   98
#define IDS_MUTE                        100
#define IDS_PLAYLISTS                   101
#define IDS_STOP_AFTER_CURRENT          102
#define IDS_HELP24                      104
#define IDS_HELP25                      105
#define IDS_HELP26                      106
#define IDS_HELP27                      107
#define IDS_HELP28                      109
#define IDS_RATE                        110
#define IDS_UNINSTALL_PROMPT            111
#define IDS_ERROR_SETTING_APPID         112
#define IDS_STRING113                   113
#define IDS_ERROR_REGISTERING_MOUSE_HOOK 113
#define IDS_MAX_BUTTONS                 114
#define IDI_ICON1                       123
#define IDI_ICON2                       124
#define IDI_ICON3                       125
#define IDI_ICON4                       126
#define IDI_ICON5                       127
#define IDI_ICON6                       128
#define IDI_ICON7                       129
#define IDI_ICON8                       130
#define IDI_ICON9                       131
#define IDI_ICON15                      132
#define IDI_ICON16                      133
#define IID_MAIN                        140
#define IDD_DIALOG1                     141
#define IDB_BACKGROUND                  142
#define IID_TAB1                        176
#define IID_TAB2                        177
#define IID_TAB3                        178
#define IID_TAB4                        179
#define IID_TAB5                        180
#define IID_TAB6                        181
#define IDI_ICON10                      193
#define IDI_ICON11                      194
#define IDI_ICON12                      195
#define IDI_ICON13                      196
#define IDI_ICON14                      197
#define IDI_ICON17                      200
#define IDD_RATEDLG                     201
#define IDI_ICON18                      208
#define IDI_ICON19                      209
#define IDI_ICON20                      210
#define IDC_BUTTON1                     1002
#define IDC_BUTTON2                     1003
#define IDC_RATE3                       1004
#define IDC_RATE4                       1005
#define IDC_RATE5                       1006
#define IDC_RATE6                       1007
#define IDC_CHECK2                      1015
#define IDC_CHECK3                      1016
#define IDC_CHECK4                      1017
#define IDC_CHECK5                      1018
#define IDC_CHECK6                      1019
#define IDC_STATIC1                     1021
#define IDC_STATIC2                     1022
#define IDC_STATIC3                     1023
#define IDC_STATIC4                     1024
#define IDC_STATIC5                     1025
#define IDC_STATIC6                     1026
#define IDC_CHECK1                      1027
#define IDC_CHECK7                      1028
#define IDC_CHECK8                      1029
#define IDC_CHECK9                      1030
#define IDC_CHECK10                     1031
#define IDC_CHECK11                     1032
#define IDC_CHECK12                     1033
#define IDC_CHECK13                     1034
#define IDC_CHECK14                     1035
#define IDC_CHECK15                     1036
#define IDC_CHECK16                     1037
#define IDC_CHECK17                     1038
#define IDC_STATIC10                    1039
#define IDC_STATIC11                    1040
#define IDC_CHECK18                     1041
#define IDC_CHECK30                     1042
#define IDC_SYSLINK1                    1043
#define IDC_SYSLINK2                    1044
#define IDC_SYSLINK3                    1045
#define IDC_SYSLINK5                    1046
#define IDC_STATIC12                    1047
#define IDC_CHECK20                     1048
#define IDC_EDIT2                       1049
#define IDC_BUTTON3                     1050
#define IDC_CHECK21                     1052
#define IDC_EDIT3                       1053
#define IDC_BUTTON4                     1054
#define IDC_RADIO1                      1055
#define IDC_RADIO42                     1056
#define IDC_RADIO4                      1056
#define IDC_RADIO5                      1057
#define IDC_RADIO2                      1057
#define IDC_RADIO3                      1058
#define IDC_EDIT4                       1059
#define IDC_RADIO7                      1060
#define IDC_BUTTON5                     1063
#define IDC_TAB                         1064
#define IDC_BUTTON6                     1069
#define IDC_CHECK25                     1070
#define IDC_CHECK26                     1071
#define IDC_BUTTON7                     1072
#define IDC_CHECK27                     1073
#define IDC_SYSLINK4                    1074
#define IDC_PCB1                        1076
#define IDC_PCB2                        1077
#define IDC_PCB3                        1078
#define IDC_PCB4                        1079
#define IDC_PCB5                        1080
#define IDC_PCB6                        1081
#define IDC_PCB7                        1082
#define IDC_PCB8                        1083
#define IDC_PCB9                        1084
#define IDC_PCB10                       1085
#define IDC_COMBO1                      1086
#define IDC_CHECK31                     1087
#define IDC_CHECK32                     1088
#define IDC_STATIC30                    1089
#define IDC_STATIC31                    1090
#define IDC_STATIC32                    1091
#define IDC_CHECK33                     1092
#define IDC_STATIC29                    1093
#define IDC_CHECK29                     1094
#define IDC_CHECK34                     1095
#define IDC_RATE2                       1096
#define IDC_CHECK35                     1096
#define IDC_BUTTON8                     1097
#define IDC_RATE1                       1098
#define IDC_CHECK36                     1099

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        215
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1099
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
